CPP = g++

CPPFLAGS = -g0 -D _DEBUG -ggdb3 -std=c++17 -O0 -Wall -Wextra -Weffc++ -Wc++14-compat                          \
-Wmissing-declarations -Wcast-align -Wcast-qual -Wchar-subscripts -Wconversion -Wctor-dtor-privacy            \
-Wempty-body -Wfloat-equal -Wformat-nonliteral -Wformat-security -Wformat=2 -Winline -Wnon-virtual-dtor 	  \
-Woverloaded-virtual -Wpacked -Wpointer-arith -Winit-self -Wredundant-decls -Wshadow -Wsign-conversion        \
-Wsign-promo -Wstrict-overflow=2 -Wsuggest-override -Wundef -Wunreachable-code \
-Wunused -Wvariadic-macros -Wno-missing-field-initializers -Wno-narrowing -Wno-old-style-cast -Wno-varargs    \
-Wstack-protector -fcheck-new -fsized-deallocation -fstack-protector -fstrict-overflow                        \
-fno-omit-frame-pointer -Wlarger-than=8192 -fPIE -Werror=vla 												  \
-fsanitize=address,alignment,bool,bounds,enum,float-cast-overflow,float-divide-by-zero,integer-divide-by-zero,nonnull-attribute,null,return,returns-nonnull-attribute,shift,signed-integer-overflow,undefined,unreachable,vla-bound,vptr

BUILD = build

SRCMODULES = input_parser.cpp tokenizer.cpp
TREE_SRC = ../tree_lib
DEBUG_MODULE = ../debug_lib/debug.cpp
TREE_MODULE = ../tree_lib/tree_funcs.cpp ../tree_lib/tree_dump.cpp
OBJMODULES = $(addprefix $(BUILD)/,$(notdir $(SRCMODULES:.cpp=.o)))
DEBUG_OBJ = $(DEBUG_MODULE:.cpp=.o)
TREE_OBJ = $(TREE_MODULE:.cpp=.o)

all: $(BUILD) $(BUILD)/front_end

$(BUILD)/front_end: main.cpp $(OBJMODULES) $(DEBUG_OBJ) $(TREE_OBJ)
	$(CPP) $(CPPFLAGS) $^ -o $@

$(BUILD)/%.o: %.cpp
	$(CPP) $(CPPFLAGS) -c $< -o $@

$(BUILD)/%.o: ../debug_lib/%.cpp
	$(CPP) $(CPPFLAGS) -c $< -o $@

$(BUILD)/%.o: ../tree_lib/%.cpp
	$(CPP) $(CPPFLAGS) -c $< -o $@

$(BUILD):
	mkdir $(BUILD)

deps.mk: $(SRCMODULES) $(DEBUG_MODULE)
	$(CPP) -MM $^ > $@

ifneq (clean, $(MAKECMDGOALS))
-include deps.mk
endif

.PHONY: clean

clean:
	rm -rf $(BUILD)
