#include "oper_structs.h"

oper_info_t oper_data[] = {{EOS, 					"\n", 			  		1,	true,		";"			},
						   {OPEN_PAR, 				"(", 			  		1,	true,		"("			},
						   {CLOSE_PAR,				")",			  		1,	true,		")"			},
						   {COMMA,					",",			  		1,	true,		","			},
						   {BLOCK_BEGIN,    		"<",			  		1,	true,		"{"			},
						   {BLOCK_END,				">",			  		1,	true,		"}"			},
						   {TAKE,					"take",			  		4,	false,		"" 			},
						   {IN_QUANTITY_OF, 		"in quantity of", 		14,	true,		"="			},
						   {ADD, 					"+", 			  		1,	true,		"+"			},
						   {SUB,					"-",			  		1,	true,		"-"			},
						   {PORTIONS_OF,			"portions of",	  		11,	true,		"*"			},
						   {DILUTED_BY,				"diluted by",     		10,	true,		"/"			},
						   {SEASONED,				"seasoned",		  		8,	true,		"sqrt"		},
						   {COOK_UNTIL, 			"cook until",	  		10,	true,		"while"		},
						   {IF,						"if",			  		2,	true,		"if"   		},
						   {OTHERWISE_IF,			"otherwise if",	  		12,	true,		"else if"	},
						   {OTHERWISE,				"otherwise",	  		9,	true,		"else"		},
						   {SERVE,					"serve",		  		5,	true,		"return"	},
						   {BUY,   					"buy",			  		3,	true,		"scanf"		},
						   {TASTE,					"taste", 		  		5,	true,		"printf"	},
						   {BON_APPETIT,			"Bon Appetit!",	  		12,	true,		"exit"		},
						   {IS_LESS_THAN,			"is less than",	  		12,	true,		"<"			},
						   {IS_LESS_OR_EQUAL_TO, 	"is less or equal to",	19,	true,		"<="		},
						   {IS_MORE_THAN, 			"is more than",			12,	true,		">"			},
						   {IS_MORE_OR_EQUAL_TO,	"is more or equal to",  19,	true,		">="		},
						   {IS_EQUAL_TO,			"is equal to",			11,	true,		"=="		},
						   {IS_NOT_EQUAL_TO,		"is not equal to",		15,	true,  		"!="		},
						   {FROM,					"from",					4,	false,		""     		},
						   {RECIPE,					"recipe",				6,  true,		"func"		}};
