#include "oper_structs.h"

oper_info_t oper_data[] = {{EOS, 					"\n", 			  		true,		";"			},
						   {OPEN_PAR, 				"(", 			  		true,		"("			},
						   {CLOSE_PAR,				")",			  		true,		")"			},
						   {COMMA,					",",			  		true,		","			},
						   {BLOCK_BEGIN,    		"<",			  		true,		"{"			},
						   {BLOCK_END,				">",			  		true,		"}"			},
						   {TAKE,					"take",			  		false,		"" 			},
						   {IN_QUANTITY_OF, 		"in quantity of", 		true,		"="			},
						   {ADD, 					"+", 			  		true,		"+"			},
						   {SUB,					"-",			  		true,		"-"			},
						   {PORTIONS_OF,			"portions of",	  		true,		"*"			},
						   {DILUTED_BY,				"diluted by",     		true,		"/"			},
						   {SEASONED,				"seasoned",		  		true,		"sqrt"		},
						   {COOK_UNTIL, 			"cook until",	  		true,		"while"		},
						   {IF,						"if",			  		true,		"if"   		},
						   {OTHERWISE_IF,			"otherwise if",	  		true,		"else if"	},
						   {OTHERWISE,				"otherwise",	  		true,		"else"		},
						   {SERVE,					"serve",		  		true,		"return"	},
						   {BUY,   					"buy",			  		true,		"scanf"		},
						   {TASTE,					"taste", 		  		true,		"printf"	},
						   {BON_APPETIT,			"bon appetit!",	  		true,		"exit"		},
						   {IS_LESS_THAN,			"is less than",	  		true,		"<"			},
						   {IS_LESS_OR_EQUAL_TO, 	"is less or equal to",	true,		"<="		},
						   {IS_MORE_THAN, 			"is more than",			true,		">"			},
						   {IS_MORE_OR_EQUAL_TO,	"is more or equal to",  true,		">="		},
						   {IS_EQUAL_TO,			"is equal to",			true,		"=="		},
						   {IS_NOT_EQUAL_TO,		"is not equal to",		true,  		"!="		}};
